CREATE DATABASE sinema
	ON PRIMARY (
					NAME = 'sinemaDb',
					FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SinemaDb.mdf',
					SIZE = 100MB,
					MAXSIZE = 500MB,
					FILEGROWTH = 50MB
				)
	LOG ON		(
					NAME = 'sinemaDb_log',
					FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SinemaDb.ldf',
					SIZE = 50MB,
					MAXSIZE = 500MB,
					FILEGROWTH = 25MB
				)
GO

USE sinema

CREATE TABLE Il (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Adi VARCHAR(20) UNIQUE NOT NULL, 
)
GO

CREATE TABLE Ilce (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Adi VARCHAR(20) NOT NULL,
	IlID INT,
	CONSTRAINT FK_ILCE FOREIGN KEY (IlID) REFERENCES Il(ID) ON DELETE SET NULL
)
GO

CREATE TABLE Sinema (
	SinemaID INT IDENTITY(1,1) PRIMARY KEY,
	Adi VARCHAR(30) UNIQUE NOT NULL,
	SalonSayisi INT NOT NULL,
	KurulusYili CHAR(4) CONSTRAINT chekKurulusYili CHECK (KurulusYili like '[0-9][0-9][0-9][0-9]') NOT NULL,
	IlID INT,
	CONSTRAINT FK_SINEMA1 FOREIGN KEY (IlID) REFERENCES Il(ID) ON DELETE SET NULL,
	IlceID INT,
	CONSTRAINT FK_SINEMA2 FOREIGN KEY (IlceID) REFERENCES Ilce(ID) ON DELETE SET NULL
)
GO

CREATE TABLE SinemaSalonu (
	SalonNumarasi INT IDENTITY(1,1) PRIMARY KEY,
	Kapasite INT NOT NULL,
	SinemaID INT,
	CONSTRAINT FK_SINEMASALONU FOREIGN KEY (SinemaID) REFERENCES Sinema(SinemaID) ON DELETE SET NULL
)
GO

CREATE TABLE Koltuk (
	KoltukNumarasi INT IDENTITY(1,1) PRIMARY KEY,
	SiraNumarasi INT NOT NULL,
	BlokNumarasi INT NOT NULL,
	SalonNumarasi INT,
	CONSTRAINT FK_KOLTUK FOREIGN KEY (SalonNumarasi) REFERENCES SinemaSalonu(SalonNumarasi) ON DELETE SET NULL
)
GO

CREATE TABLE Film (
	FilmID INT IDENTITY(1,1) PRIMARY KEY,
	Adi VARCHAR(30) UNIQUE NOT NULL, 
	ImdbPuani CHAR(3) CONSTRAINT chekImdb CHECK (ImdbPuani like '[0-9].[0-9]') NOT NULL,
	Sure CHAR(3) CONSTRAINT chekSure CHECK (Sure like '[0-9][0-9][0-9]') NOT NULL,
	Butce MONEY NOT NULL,
	Aciklama VARCHAR(200) NOT NULL,
	CekildigiYil CHAR(4) CONSTRAINT chekCekildigiYil CHECK (CekildigiYil like '[0-9][0-9][0-9][0-9]') NOT NULL
)
GO

CREATE TABLE FilmKategori (
	KategoriID INT IDENTITY(1,1) PRIMARY KEY,
	Adi VARCHAR(30) UNIQUE NOT NULL, 
)
GO

CREATE TABLE HangiFilmHangiKategori (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	FilmID INT,
	CONSTRAINT FK_HFHK FOREIGN KEY (FilmID) REFERENCES Film(FilmID) ON DELETE SET NULL,
	KategoriID INT,
	CONSTRAINT FK_HFHK2 FOREIGN KEY (KategoriID) REFERENCES FilmKategori(KategoriID) ON DELETE SET NULL
)
GO

CREATE TABLE Gorev (
	GorevID INT IDENTITY(1,1) PRIMARY KEY,
	Adi VARCHAR(30) UNIQUE NOT NULL, 
)
GO

CREATE TABLE Ekip (
	EkipID INT IDENTITY(1,1) PRIMARY KEY,
	Adi VARCHAR(50) NOT NULL, 
	Soyadi VARCHAR(50) NOT NULL, 
	DogumTarihi DATE NOT NULL,
	Yas AS DATEDIFF(yy,DogumTarihi,GETDATE()),
	Cinsiyet CHAR(1) CONSTRAINT chekCinsiyet CHECK (Cinsiyet like '[EK]') NOT NULL -- kadýn: K, erkek: E
)
GO

CREATE TABLE HangiFilmHangiEkipHangiGorev (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	FilmID INT,
	CONSTRAINT FK_HFHEHG FOREIGN KEY (FilmID) REFERENCES Film(FilmID) ON DELETE SET NULL,
	GorevID INT,
	CONSTRAINT FK_HFHEHG2 FOREIGN KEY (GorevID) REFERENCES Gorev(GorevID) ON DELETE SET NULL,
	EkipID INT,
	CONSTRAINT FK_HFHEHG3 FOREIGN KEY (EkipID) REFERENCES Ekip(EkipID) ON DELETE SET NULL
)
GO

CREATE TABLE Seans (
	SeansID INT IDENTITY(1,1) PRIMARY KEY,
	Gun VARCHAR(10) CONSTRAINT checkGun CHECK (Gun in ('pazartesi','salý','çarþamba','perþembe','cuma','cumartesi','pazar')) NOT NULL,
	Saat CHAR(5) CONSTRAINT chekSaat CHECK (Saat like '[0-9][0-9]:[0-9][0-9]') NOT NULL,
	FilmID INT,
	CONSTRAINT FK_SEANS FOREIGN KEY (FilmID) REFERENCES Film(FilmID) ON DELETE SET NULL
)
GO

CREATE TABLE HangiSalonHangiSeans (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	SalonNumarasi INT,
	CONSTRAINT FK_HSHS1 FOREIGN KEY (SalonNumarasi) REFERENCES SinemaSalonu(SalonNumarasi) ON DELETE SET NULL,
	SeansID INT,
	CONSTRAINT FK_HSHS2 FOREIGN KEY (SeansID) REFERENCES Seans(SeansID) ON DELETE SET NULL
)
GO

CREATE TABLE Seyirci (
	SeyirciID INT IDENTITY(1,1) PRIMARY KEY,
	Adi VARCHAR(20) NOT NULL, 
	Soyadi VARCHAR(30) NOT NULL, 
	DogumTarihi DATE NOT NULL,
	Yas AS DATEDIFF(yy,DogumTarihi,GETDATE()),
	Cinsiyet CHAR(1) CONSTRAINT chekCinsiyet2 CHECK (Cinsiyet like '[EK]') NOT NULL, -- kadýn: K, erkek: E
	Mail VARCHAR(50) UNIQUE CONSTRAINT chekMail CHECK (Mail like '%@%.%') NOT NULL,
	IlID INT,
	CONSTRAINT FK_SEYIRCI1 FOREIGN KEY (IlID) REFERENCES Il(ID) ON DELETE SET NULL,
	IlceID INT,
	CONSTRAINT FK_SEYIRCI2 FOREIGN KEY (IlceID) REFERENCES Ilce(ID) ON DELETE SET NULL
)
GO

CREATE TABLE Bilet (
	BiletID INT IDENTITY(1,1) PRIMARY KEY,
	BiletFiyati MONEY NOT NULL,
	GosterimTarihi DATE NOT NULL,
	KesimTarihi DATE NOT NULL,
	BiletDurumu CHAR(1) CONSTRAINT chekDurum CHECK (BiletDurumu like '[0-1]') NOT NULL, -- aktif: 1 , pasif: 0
	FilmID INT,
	CONSTRAINT FK_BILET1 FOREIGN KEY (FilmID) REFERENCES Film(FilmID) ON DELETE SET NULL,
	SeansID INT,
	CONSTRAINT FK_BILET2 FOREIGN KEY (SeansID) REFERENCES Seans(SeansID) ON DELETE SET NULL,
	SalonNumarasi INT,
	CONSTRAINT FK_BILET3 FOREIGN KEY (SalonNumarasi) REFERENCES SinemaSalonu(SalonNumarasi) ON DELETE SET NULL,
	KoltukNumarasi INT,
	CONSTRAINT FK_BILET4 FOREIGN KEY (KoltukNumarasi) REFERENCES Koltuk(KoltukNumarasi) ON DELETE SET NULL,
	SinemaID INT,
	CONSTRAINT FK_BILET5 FOREIGN KEY (SinemaID) REFERENCES Sinema(SinemaID) ON DELETE SET NULL,
	SeyirciID INT,
	CONSTRAINT FK_BILET6 FOREIGN KEY (SeyirciID) REFERENCES Seyirci(SeyirciID) ON DELETE SET NULL
)
GO